trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

stages:
# ---------------------------------------
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'
    - task: AdvancedSecurity-Dependency-Scanning@1
    - task: AdvancedSecurity-Publish@1
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'javascript'
        querysuite: 'security-and-quality'
    - task: AdvancedSecurity-Codeql-Analyze@1

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        command: 'custom'
        customCommand: 'run build'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: 'build'
        ArtifactName: 'drop'
        publishLocation: 'Container'
#---------------------------------------
- stage: Test
  displayName: 'Test Stage'
  dependsOn: Build
  jobs:
  - job: RunTests
    displayName: 'Run Unit/Integration Tests'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - checkout: self
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        command: 'install'

    - task: Npm@1
      displayName: 'npm test'
      inputs:
        command: 'custom'
        customCommand: 'run test -- --ci --watchAll=false'
        

# ---------------------------------------
- stage: Deploy_Dev
  displayName: 'Deploy to Dev'
  dependsOn: Build
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy to Dev Environment'
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@5
            displayName: 'Deploy webapp-dev'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'ME-MngEnvMCAP843502-v-shipradhan-1 (c5ade1be-3e22-415a-adf2-b3ec2fc417ec)'
              appType: 'webAppLinux'
              WebAppName: 'webapp-project'
              packageForLinux: '$(System.ArtifactsDirectory)/drop'
              RuntimeStack: 'STATICSITE|1.0'
              DeploymentTypeLinux: 'oneDeploy'

# ---------------------------------------
- stage: Deploy_Test
  displayName: 'Deploy to Test'
  dependsOn: Deploy_Dev
  jobs:
  - deployment: DeployTest
    displayName: 'Deploy to Test Environment'
    environment: 'test'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureRmWebAppDeployment@5
            displayName: 'Deploy webapp-test'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'web-app-test'
              appType: 'webAppLinux'
              WebAppName: 'webapp-project-test'
              packageForLinux: '$(System.ArtifactsDirectory)/drop'
              RuntimeStack: 'STATICSITE|1.0'
              DeploymentTypeLinux: 'oneDeploy'
